### ISSUE TITLE
Use file ending *.sl for all OperatorDefs and Tests

### ISSUE THREAD

**Issue by td5r** [Bitspark/slang#123]
Currently we support YAML and JSON files for describing Operators and TestCases.
We have to deal with following issues:
 - same OperatorDef could exists in 2 versions (YAML & JSON) distinguished by corresponding file ending
 - currently we won't discover files ending with *.yml (missing *a*)
 - we have to search for multiple file endings

**BUT**

what, if we use *.sl as file ending instead of *.yaml or *.json.
The actual content helps us to distinguish between JSON and YAML...
Valid json neads surrounding "{" "}" and yaml must begin with "---"

inspiration source: https://gohugo.io/content-management/front-matter/#front-matter-formats

**Comment by Kaligule** [comment]
> yaml must begin with "---"

I am not so sure that they have to. The [YAML Reference Parser](http://ben-kiki.org/ypaste/) linked on http://yaml.org/ parses documents without the dashes quite fine.

The [reference](http://yaml.org/spec/1.2/spec.html#id2760395) says:

> YAML uses three dashes (“---”) to separate directives from document content

I can't find information in the specification whether [directives](http://yaml.org/spec/1.2/spec.html#directive//) are necessary and whether the dashes can be omitted if none are present. [Other sources](https://camel.readthedocs.io/en/latest/yamlref.html) tell that it is optional, though.

**Comment by kairichard** [comment]
@Kaligule thanks for your input - we since then decided to close this issues.
