### ISSUE TITLE
Choring

### ISSUE THREAD

**Issue by td5r** [Bitspark/slang#28]
- [x] move *builtin_function_test.go* into *slang/builtin/*
- [x] Rename `builtin.MakeOperator` to `builtin.NewOperator`
- [x] Don't use `builtin.MakeOperator` within `builtin` operator tests
- [x] Rename constructor functions beginning with `Make...` into `New...`
- [x] Move all `...Def` structs in separate file *slang/op/def.go*
- [x] Extend Assertions by `Assertions.PortPushes`
- [x] Rename `ParseConnection` into `ParsePort`
- [x] Move functions `Parse...Def` from package `slang/op` into `slang`
- [X] Rename `slang/op` into `slang/core`
  
@jm9e

**Comment by jm9e** [comment]
I think `builtin.NewOperator` instead of `builtin.NewOperatorInstance` would do, wouldn't it?
Otherwise we would have to rename `op.MakeOperator` to `op.NewOperatorInstance` as well.

**Comment by td5r** [comment]
New Suggestions. Choose 1:
Rename `slang/op` into
- [x] `slang/core`
- [ ] `slang/lib`
- [ ] `slang/components`
- [x] `slang/op` (no renaming)
