### ISSUE TITLE
Generic operators

### ISSUE THREAD

**Issue by td5r** [Bitspark/slang#38]
Make Port of type="Any" allow passing items of any streams, maps or primitives.

Currently type="Any" just means a primitive of any datatype

**Comment by jm9e** [comment]
The port definition should be derived from the connection then

**Comment by jm9e** [comment]
We will need to add a `ports` field to `InstanceDef` to allow instancing operators which have unconnected ANY ports. That way we can make the Suite test run again even before completely implementing type inference.
