### ISSUE TITLE
Don't replace '.' in numbers and strings in builtin.Eval

### ISSUE THREAD

**Issue by jm9e** [Bitspark/slang#50]
* Have a look at govaluate tokens

**Comment by jm9e** [comment]
This could be useful: https://github.com/Knetic/govaluate/blob/master/TokenKind.go

**Comment by kairichard** [comment]
https://github.com/PaesslerAG/gval/ might be useful here.

**Comment by kairichard** [comment]
@jm9e `evaluate` does now indeed use `govaluate` - can this be closed?
