### ISSUE TITLE
Implement builtin/stdlib operators for system calls and more

### ISSUE THREAD

**Issue by jm9e** [Bitspark/slang#56]
* File system
  - read file
  - read directory
* Parsing
  - csv, json, xml, yaml, ...
* Compression
  - zip, bz2, gzip, ...
* Cryptography
* Network
  - TCP, UDP
  - HTTP server & client
  - Send email
  - DNS lookup
* Math
  - sum, avg, min, max, ...
* DS/Algos
  - sort
  - find
* OS
  - exec
  - environment
* Date & Time
  - now

**Comment by td5r** [comment]
Maybe some of them could be implemented as part of stdlib e.g.: math function could be implemented as evals.

**Comment by jm9e** [comment]
You are absolutely right. I got confused there. We should split it into STDLIB and BUILTINS.
